# Generated by Django 5.1 on 2024-09-13 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('owners', models.ManyToManyField(related_name='items', to='backend_api.person')),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('save_date', models.DateField()),
                ('items', models.ManyToManyField(related_name='receipts', to='backend_api.item')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='backend_api.person')),
            ],
        ),
    ]
