# Generated by Django 5.1 on 2024-09-13 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='payer',
        ),
        migrations.AddField(
            model_name='receipt',
            name='payer',
            field=models.ManyToManyField(related_name='receipts', to='backend_api.person'),
        ),
    ]
