# Generated by Django 5.1 on 2024-09-14 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0002_remove_receipt_payer_receipt_payer'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Person',
            new_name='PersonPayer',
        ),
        migrations.AlterField(
            model_name='item',
            name='owners',
            field=models.ManyToManyField(related_name='items', to='backend_api.personowner'),
        ),
    ]
