# Generated by Django 5.1 on 2024-09-14 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0004_item_category_item_quantity_item_save_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='save_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
