# Generated by Django 5.1 on 2024-09-14 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0005_alter_item_save_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='save_date',
        ),
    ]
