# Generated by Django 5.1 on 2024-09-14 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0006_remove_item_save_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='save_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='save_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
