# Generated by Django 5.1 on 2024-09-14 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0007_item_save_date_alter_receipt_save_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='owners',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='payer',
        ),
        migrations.DeleteModel(
            name='PersonOwner',
        ),
        migrations.AddField(
            model_name='item',
            name='owners',
            field=models.JSONField(default=list),
        ),
        migrations.DeleteModel(
            name='PersonPayer',
        ),
        migrations.AddField(
            model_name='receipt',
            name='payer',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=10),
        ),
    ]
