# Generated by Django 5.1 on 2024-09-14 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0008_person_remove_item_owners_remove_receipt_payer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='owner',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='person',
            name='payer',
            field=models.BooleanField(default=False),
        ),
    ]
