# Generated by Django 5.1 on 2024-09-15 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0011_rename_owners_item_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='shop',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
