# Generated by Django 5.1 on 2024-09-20 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0013_alter_item_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('fuel', 'Paliwo'), ('car_expenses', 'Wydatki na samochód'), ('fastfood', 'Fast Food'), ('alcohol', 'Alkohol'), ('food_drinks', 'Picie & jedzenie'), ('chemistry', 'Chemia'), ('clothes', 'Ubrania'), ('electronics_games', 'Elektornika & gry'), ('tickets_entrance', 'Bilety & wejściówki'), ('other_shopping', 'Inne zakupy'), ('flat_bills', 'Rachunki za mieszkanie'), ('monthly_subscriptions', 'Miesięczne subskrypcje'), ('other_cyclical_expenses', 'Inne cykliczne wydatki'), ('investments_savings', 'Inwestycje & oszczędności'), ('other', 'Inne'), ('for_study', 'Na studia'), ('work_income', 'Przychód z pracy'), ('family_income', 'Przychód od rodziny'), ('investments_income', 'Przychód z inwestycji'), ('money_back', 'Zwrot pieniędzy'), ('last_month_balance', 'Saldo z poprzedniego miesiąca')], max_length=255),
        ),
    ]
