# Generated by Django 5.1 on 2024-09-24 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0015_investment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Investment',
        ),
    ]
