# Generated by Django 5.1 on 2025-01-24 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0017_alter_item_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='owner',
        ),
        migrations.AddField(
            model_name='item',
            name='owners',
            field=models.JSONField(default=list),
        ),
    ]
