# Generated by Django 5.1 on 2025-01-27 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0019_remove_item_owners_item_owners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='payer',
            field=models.ForeignKey(limit_choices_to={'payer': True}, on_delete=django.db.models.deletion.CASCADE, related_name='payer_receipts', to='backend_api.person'),
        ),
    ]
