# Generated by Django 5.1 on 2025-01-27 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0020_alter_receipt_payer'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('last_used', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='receipt',
            name='shop',
            field=models.CharField(max_length=255),
        ),
    ]
