# Generated by Django 5.1 on 2025-02-18 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0023_alter_itemprediction_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nazwa lub symbol inwestycji', max_length=100)),
                ('invested', models.DecimalField(decimal_places=2, default=0, help_text='Kwota wpłacona', max_digits=12)),
                ('current_value', models.DecimalField(decimal_places=2, default=0, help_text='Aktualna wartość inwestycji', max_digits=12)),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='Data ostatniej aktualizacji')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Data transakcji')),
                ('type', models.CharField(choices=[('deposit', 'Wpłata'), ('withdrawal', 'Wypłata'), ('dividend', 'Dywidenda')], help_text='Typ transakcji', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Kwota transakcji', max_digits=12)),
                ('notes', models.TextField(blank=True, help_text='Dodatkowe informacje', null=True)),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='backend_api.investment')),
            ],
        ),
    ]
