# Generated by Django 5.1 on 2025-02-18 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0024_investment_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='source_item_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
