name: Build frontend with npm

on:
    push: # uruchamiaj zawsze, na każdą gałąź
        branches:
            - "**"

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: frontend_ztp # wszystkie polecenia w ./frontend_ztp

        steps:
            # 1️⃣ Klon repo
            - uses: actions/checkout@v4

            # 2️⃣ Node + cache dla npm
            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 22 # lub inna wersja Node
                  cache: npm # cache ~/.npm

            # 3️⃣ Instalacja zależności
            - name: Install dependencies
              run: npm ci --legacy-peer-deps # szybciej i deterministycznie

            # 4️⃣ Budowanie projektu
            - name: Build project
              run: npm run build

            # 5️⃣ Artefakt z buildem
            - name: Upload dist folder
              uses: actions/upload-artifact@v4
              with:
                  name: dist
                  path: |
                      frontend_ztp/dist
                      !frontend_ztp/dist/**/*.map   # np. pomiń source-mapy
